parameters:
    stash.cache.class:      Tedivm\StashBundle\Service\CacheService
    stash.logger.class:     Tedivm\StashBundle\Service\CacheLogger
    stash.handler.class:    Tedivm\Stash\Handler\HandlerInterface
    stash.factory.class:    Tedivm\StashBundle\Factory\HandlerFactory

services:
    stash.cache:
        class:                %stash.cache.class%
        abstract:           true
    stash.logger:
        class:                %stash.logger.class%
        abstract:           true
    stash.handler:
        class:              %stash.handler.class%
        abstract:           true
        synthetic:          true
        factory_method:     createHandler
        factory_class:      %stash.factory.class%
    data_collector.stash:
        class:      Tedivm\StashBundle\Collector\CacheDataCollector
        arguments: [ %stash.default_cache%, %stash.caches%, %stash.caches.options% ]
        tags:
            -
                name: data_collector
                template: "TedivmStashBundle:Profiler:layout"
                id: "stash"